### ISSUE TITLE
Error message when custom marker image is set TYPO3 11.5.26, go_maps_ext >=5

### ISSUE THREAD

**Issue by erru0000** [mhirdes/go_maps_ext#102]
After updating from 10.4 to 11.5 and go_maps from 4 to 5 or 6, "oops an error occurred" occurs on page where go_maps_ext is embedded. In the log file I found the issue with the marker image. The image and the image path is all working fine. It was working perfectly in 10.4 but not anymore. Deactivating the custom markers brings the map back but not with custom markers which are essential for us...

here a part of the error log:

`[ALERT] request="2194192f12f01" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 202304131054584d8029a1- Exception: Supplied https://.../custommarker.jpg could not be resolved to a File or FileReference., in file /typo3_src-11.5.26/typo3/sysext/fluid/Classes/ViewHelpers/Uri/ImageViewHelper.php:166 - {"exception":"UnexpectedValueException: Supplied https://.../custommarker.jpg could not be resolved to a File or FileReference. in /typo3_src-11.5.26/typo3/sysext/extbase/Classes/Service/ImageService.php:142\nStack`

I also tried uploading a new image as custom marker but the same problem. Tested all with PHP 7.4, 8.0 and 8.1

**Comment by mhirdes** [comment]
hey, sry for the late response. If you like, we can take a look together. Write me on Slack
