### ISSUE TITLE
Uncaught (in promise) TypeError: el.gomapsext.controller is undefined

### ISSUE THREAD

**Issue by t3touch** [mhirdes/go_maps_ext#106]
I got this JS error in a TYPO3 11. What is to do to make the map working? In the BE address record the map is shown, but not in the FE.

**Comment by mediaessenz** [comment]
Same problem under TYPO3 12.

**Comment by mhirdes** [comment]
Did you include the JS from the extension?

**Comment by mediaessenz** [comment]
Yes.

Meanwhile, I got it working, by moving the js to the header and activate the preview

Extension Settings:
```
'go_maps_ext' => [
            'footerJS' => '1',
            'include_google_api_manually' => '0',
            'include_manually' => '1',
        ],
```

Constants:
```
plugin.tx_gomapsext {
    settings {
        apiKey = YXZ....
        preview  {
            enabled = 1
            setCookieToShowMapAlways = 1
        }
    }
}
```

Setup:
```
page {
    includeJS {
        markerclusterer_compiled = EXT:go_maps_ext/Resources/Public/Scripts/markerclusterer_compiled.js
        gomapsext = EXT:go_maps_ext/Resources/Public/Scripts/gomapsext.js
        gomapsext_preview = EXT:go_maps_ext/Resources/Public/Scripts/gomapsext.preview.js
    }
}

**Comment by quadronet** [comment]
I have the same problem, TYPO3 11.5.27 latest version from go_maps_ext.

Uncaught (in promise) ge {message: 'goMapsExtLoaded is not a function', stack: 'Error\n    at new ge (https://maps.google.com/maps/…y=myapikey:246:231', name: 'InvalidValueError'}

https://www.augen.1qn.de/kontakt/anfahrt

The map isn´t loading....

**Comment by mhirdes** [comment]
Does the latest dev version help you?

**Comment by quadronet** [comment]
Sorry, no. The same:Uncaught (in promise) ge {message: 'goMapsExtLoaded is not a function', stack: 'Error\n    at new ge (https://maps.google.com/maps/…0tXKs9ZZwgP6YrSdfdfen9kc2RFebM&language=de:246:231', name: 'InvalidValueError'}

**Comment by mhirdes** [comment]
May we can take a look together? Can you contact me tomorrow morning on slack?

**Comment by quadronet** [comment]
Problem behoben, eine extension hatte jquery eingebunden, damit lief es nicht. 

Nachdem ich selbst jquery 3.7 mit forceOnTop eingebunden habe läuft es. Aber ich  habe nur die Version 5.1 genutzt. Mit der 6. Geht es nicht, karte wird gar nicht geladen, mit 5.1 schon. 


Aber mit Fehlern:

 

https://ege.1qn.de/kontakt/anfahrt  PHP 8.2 . 

 

Komischerweise hier nicht: https://augen.1qn.de/kontakt/anfahrt  PHP 8.1




Dirk Wohlrabe

Kundenzufriedenheit: 

Bitte beurteilen Sie uns bei Google unter:  <https://g.page/r/CSTq2YN1HkIZEB8/review> https://g.page/r/CSTq2YN1HkIZEB8/review

 

 

Büro und Fotostudio:

DER FOTORABE - Fa. QUADRONET® 
Kapeller Str. 19
76887 Bad Bergzabern



✉E-Mail :  ***@***.***> ***@***.***
✉E-Mail Fotostudio:  ***@***.***> ***@***.*** 


☎Fon (mobil): +49 170 / 555 6009
☎Fon 1: +49 63 43 / 988 56 98
☎Fon 2: +49 63 43 / 931 525 
☎Fax: +49 63 43 / 931 526

☑FACEBOOK:   <https://www.facebook.com/quadronet/> https://www.facebook.com/quadronet/
☑FACEBOOK Fotorabe:   <https://www.facebook.com/fotorabe> https://www.facebook.com/fotorabe

☑SKYPENAME:  QUADRONET
☑TWITTER:       QUADRONET

 

Rechnungsadresse:

Fa. QUADRONET® u. DER FOTORABE
Geschäftsinhaberin Nadine Wohlrabe 
Maxburgring 40b 
76887 Bad Bergzabern 


Pflichtinformationen gemäß Artikel 13 DSGVO
Im Falle des Erstkontakts sind wir gemäß Art. 12, 13 DSGVO verpflichtet, Ihnen folgende datenschutzrechtliche Pflichtinformationen zur Verfügung zu stellen: Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre personenbezogenen Daten nur, soweit an der Verarbeitung ein berechtigtes Interesse besteht (Art. 6 Abs. 1 lit. f DSGVO), Sie in die Datenverarbeitung eingewilligt haben (Art. 6 Abs. 1 lit. a DSGVO), die Verarbeitung für die Anbahnung, Begründung, inhaltliche Ausgestaltung oder Änderung eines Rechtsverhältnisses zwischen Ihnen und uns erforderlich sind (Art. 6 Abs. 1 lit. b DSGVO) oder eine sonstige Rechtsnorm die Verarbeitung gestattet. Ihre personenbezogenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen – insbesondere steuer- und handelsrechtliche Aufbewahrungsfristen – bleiben unberührt. Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Ihnen steht außerdem ein Recht auf Widerspruch, auf Datenübertragbarkeit und ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu. Ferner können Sie die Berichtigung, die Löschung und unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten verlangen. Details entnehmen Sie unserer  <https://quadronet.de/kontakt/datenschutzerklaerung/> Datenschutzerklärung.

 



 

 

Von: mhirdes ***@***.***> 
Gesendet: Montag, 12. Juni 2023 13:16
An: mhirdes/go_maps_ext ***@***.***>
Cc: Quadronet ® Internetlösungen ***@***.***>; Comment ***@***.***>
Betreff: Re: [mhirdes/go_maps_ext] Uncaught (in promise) TypeError: el.gomapsext.controller is undefined (Issue #106)

 

May we can take a look together? Can you contact me tomorrow morning on slack?

**Comment by quadronet** [comment]
Vergiss die Fehler, das kommt von einer anderen Ext…. 

 

Mit freundlichen Grüßen
Dirk Wohlrabe

Kundenzufriedenheit: 

Bitte beurteilen Sie uns bei Google unter:  <https://g.page/r/CSTq2YN1HkIZEB8/review> https://g.page/r/CSTq2YN1HkIZEB8/review

 

 

Büro und Fotostudio:

DER FOTORABE - Fa. QUADRONET® 
Kapeller Str. 19
76887 Bad Bergzabern



✉E-Mail :  ***@***.***> ***@***.***
✉E-Mail Fotostudio:  ***@***.***> ***@***.*** 


☎Fon (mobil): +49 170 / 555 6009
☎Fon 1: +49 63 43 / 988 56 98
☎Fon 2: +49 63 43 / 931 525 
☎Fax: +49 63 43 / 931 526

☑FACEBOOK:   <https://www.facebook.com/quadronet/> https://www.facebook.com/quadronet/
☑FACEBOOK Fotorabe:   <https://www.facebook.com/fotorabe> https://www.facebook.com/fotorabe

☑SKYPENAME:  QUADRONET
☑TWITTER:       QUADRONET

 

Rechnungsadresse:

Fa. QUADRONET® u. DER FOTORABE
Geschäftsinhaberin Nadine Wohlrabe 
Maxburgring 40b 
76887 Bad Bergzabern 


Pflichtinformationen gemäß Artikel 13 DSGVO
Im Falle des Erstkontakts sind wir gemäß Art. 12, 13 DSGVO verpflichtet, Ihnen folgende datenschutzrechtliche Pflichtinformationen zur Verfügung zu stellen: Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre personenbezogenen Daten nur, soweit an der Verarbeitung ein berechtigtes Interesse besteht (Art. 6 Abs. 1 lit. f DSGVO), Sie in die Datenverarbeitung eingewilligt haben (Art. 6 Abs. 1 lit. a DSGVO), die Verarbeitung für die Anbahnung, Begründung, inhaltliche Ausgestaltung oder Änderung eines Rechtsverhältnisses zwischen Ihnen und uns erforderlich sind (Art. 6 Abs. 1 lit. b DSGVO) oder eine sonstige Rechtsnorm die Verarbeitung gestattet. Ihre personenbezogenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen – insbesondere steuer- und handelsrechtliche Aufbewahrungsfristen – bleiben unberührt. Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Ihnen steht außerdem ein Recht auf Widerspruch, auf Datenübertragbarkeit und ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu. Ferner können Sie die Berichtigung, die Löschung und unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten verlangen. Details entnehmen Sie unserer  <https://quadronet.de/kontakt/datenschutzerklaerung/> Datenschutzerklärung.

 



 

 

Von: mhirdes ***@***.***> 
Gesendet: Montag, 12. Juni 2023 13:16
An: mhirdes/go_maps_ext ***@***.***>
Cc: Quadronet ® Internetlösungen ***@***.***>; Comment ***@***.***>
Betreff: Re: [mhirdes/go_maps_ext] Uncaught (in promise) TypeError: el.gomapsext.controller is undefined (Issue #106)

 

May we can take a look together? Can you contact me tomorrow morning on slack?
