### ISSUE TITLE
goMapsExtController cached in goMapsExtControllerStorage, when goMapsExtLoaded is called.

### ISSUE THREAD

**Issue by slavlee** [mhirdes/go_maps_ext#107]
There is a chance that there is nothing inside the variable: goMapsExtControllerStorage, when the callback is executed.

In this case JS error occures due no return value check, when calling initialize() and no map is shown as well.

One possible workaround is to change the goMapsExtLoaded as follows:

```
window.goMapsExtLoaded = function() {
  const maps = document.querySelectorAll('.js-map');
  maps.forEach(function (el) {
    const goMapsExtController = getGoMapsExtControllerById(el.id);
    
    if (goMapsExtController) {
      goMapsExtController.initialize();
    }else {
      // if not search controller loaded, then retry 
      // after 250ms
      console.log("No controller found. We retry in 250ms");
      setTimeout(goMapsExtLoaded, 250);
    }
  });
}
```

**Comment by mhirdes** [comment]
Thanks for the workaround. The fix is online

**Comment by riegeo** [comment]
Thanks for this workaround. I had this Problem on every website with TYPO3 12.
`Uncaught (in promise) InvalidValueError: goMapsExtLoaded is not a function`

Now the maps work again.
