### ISSUE TITLE
Uncaught (in promise) TypeError: getGoMapsExtControllerById(...) is undefined

### ISSUE THREAD

**Issue by mediaessenz** [mhirdes/go_maps_ext#109]
Sometimes it happens, that a map is not shown and this error appears in the js console:
Uncaught (in promise) TypeError: getGoMapsExtControllerById(...) is undefined

I think it's a timing problem, if cached js is used or not.

I could imagine, that this can be fixed by wrapping the `getGoMapsExtControllerById(el.id).initialize();` call in a DOMContentLoaded event listener like so:
```javascript
window.goMapsExtLoaded = function() {
    document.addEventListener('DOMContentLoaded', () => {
        const maps = document.querySelectorAll('.js-map');
        maps.forEach(function (el) {
            getGoMapsExtControllerById(el.id).initialize();
        });
    })
}
```

**Comment by mhirdes** [comment]
This should fix the error. Maybe you can test it?

**Comment by mediaessenz** [comment]
Why not using the DOMContentLoaded event? 

This event is fired exact at that time when the DOM content is loaded. This way it is not neccecarey to check the readystate in a loop ...

**Comment by mhirdes** [comment]
Thanks for your feedback. What about this solution? The problem is, that it can be that the event was already triggered and the API and so the callback function was not loaded.

So I have to check both, the DOM is ready and the API was loaded.

**Comment by mediaessenz** [comment]
Just changing setTimeout with a DOMContentLoaded listener will not work imo.
How do you load the api code?

**Comment by mhirdes** [comment]
I wrote you a message via Slack. Maybe we can chat there

**Comment by nordowl** [comment]
Any updates on this? The proposed fix sadly doesn't work for me as it introduces a new error:
`Uncaught (in promise) TypeError: this.gme is undefined`

**Comment by mhirdes** [comment]
Did you test the current main branch?

**Comment by nordowl** [comment]
I didn't. Will test again using the updated branch and report back.

**Comment by ingeniumdesign** [comment]
we have the same problem:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'initialize')`

**Comment by mhirdes** [comment]
Please use the current version 6.1.1
