### ISSUE TITLE
Support for high resolution markers

### ISSUE THREAD

**Issue by stefanschleich** [mhirdes/go_maps_ext#11]
If I get this right there's no option for using high resolution markers as google does for example with their logo on the map. In other google maps integrations you can just add the marker image for example in double the size and change the dimensions of the marker to half of that (works great for 2x retina devices). If I do this with this extension the marker image just gets cropped. Is there a way to get something like this with the current version?

**Comment by mhirdes** [comment]
Yes there would be a way. but I currently don't have much time for this. May you can send a pull request?

**Comment by mhirdes** [comment]
OK, i tried a small fix. Please try the current version and give me feedback.

**Comment by stefanschleich** [comment]
This kind of works as the image is now scaled down instead of being cropped, but it still seems to be internally processed to get the given size instead of just scaling it down in the frontend-output.

Tested with v1.7.1 of go_maps_ext but I think the version is not relevant to this behaviour.

**Comment by mhirdes** [comment]
Sry for the long pause. Now I double the size of the marker an scale them down in the frontend. So the image you use should be at least two times bigger then the width and hight you enter. Maybe you can try the current dev version.
