### ISSUE TITLE
Google Maps JavaScript API has been loaded directly without a callback

### ISSUE THREAD

**Issue by averlon** [mhirdes/go_maps_ext#110]
After changing from clickstorm/go_maps_ext to clickstorm/go-maps-ext I get the error message in the Java-Script Console:

```
Google Maps JavaScript API has been loaded directly without a callback. This is not supported and can lead to race conditions and suboptimal performance. For supported loading patterns please see https://goo.gle/js-api-loading
```

What could be the reason for this?
T3: 11.5.33
go-maps-ext: 6.1.0

**Comment by mhirdes** [comment]
Do you include the Google Maps JavaScript manually?

**Comment by mhirdes** [comment]
Not really. Please take a look in your code in the frontend. How is the API called. Usually there should be a script tag like this:

`<script src="//maps.google.com/maps/api/js?v=weekly&amp;callback=goMapsExtLoaded&amp;key=xxxxxx&amp;language=de" type="text/javascript" async="async"></script>`
