### ISSUE TITLE
map does not always load

### ISSUE THREAD

**Issue by alsodenn** [mhirdes/go_maps_ext#112]
We have made various TYPO3 updates to LTS 11 and also updated the go_maps_ext extension. We have the same problems everywhere. The maps are not always loaded. The problem mainly affects Google Chrome/Safari. Firefox does not seem to have this problem. This bugfix helps a bit (the map loads more often as before but still not always): https://github.com/mhirdes/go_maps_ext/commit/e470e977066c319956f593a3d44473ae81c7f8d8

It seems that the callback function "goMapsExtLoaded" is not always called or has a wrong timing:
![screen1](https://github.com/mhirdes/go_maps_ext/assets/906053/3f467022-f9c1-4ae9-85d4-f77fb240dc09)

Another input:
The behaviour described above shows up with the "basic.footerJS" setting enabled. If the scripts are inserted in the header, the following error message appears if the map is not displayed:
![screen2](https://github.com/mhirdes/go_maps_ext/assets/906053/ff49aff7-ed8a-44b9-aa1e-a4d0452379fe)

In the cases where the map is displayed, this error message appears but the map still appears, this is due to the bugfix/workaround mentioned above:
![screen1](https://github.com/mhirdes/go_maps_ext/assets/906053/3f467022-f9c1-4ae9-85d4-f77fb240dc09)

I don't know what the error is and hope to help find the error with this input. Thanks for checking it out.I don't know what the error is and hope to help find the error with this input. Thanks for checking it out.

**Comment by mhirdes** [comment]
can you try the current main branch?

**Comment by alsodenn** [comment]
I have tested the current branch on two instances and it now works perfectly!
Thank you!

**Comment by mhirdes** [comment]
Thanks for testing
