### ISSUE TITLE
Google Maps JavaScript API has been loaded directly without loading=async

### ISSUE THREAD

**Issue by ingeniumdesign** [mhirdes/go_maps_ext#115]
Hi, i have a frontend error:

> Google Maps JavaScript API has been loaded directly without loading=async. This can result in suboptimal performance. For best-practice loading patterns please see https://goo.gle/js-api-loading

TYPO3 v12
go_maps_ext Version = github main latest

**Frontend Loading:**
```
<script>
/*<![CDATA[*/
/*txGoMapsExtLibrary*/
window.txGoMapsExtLibrary = "//maps.google.com/maps/api/js?v=weekly&callback=goMapsExtLoaded&key=XXXX&language=de";

/*]]>*/
</script>
```

**Comment by mhirdes** [comment]
Please take a look at the current version 6.1.1

Resources/Public/Scripts/gomapsext.js, line 739

`document.addEventListener("DOMContentLoaded", () => {
  // add global callback function, see https://developers.google.com/maps/documentation/javascript/overview#Loading_the_Maps_API
  window.goMapsExtLoaded = function () {
      const maps = document.querySelectorAll('.js-map');
      maps.forEach(function (el) {
        el.gomapsext.controller = new GoMapsExtController(el, el.gomapsext.gme);
        el.gomapsext.controller.initialize();
      });
  };

  if(window.txGoMapsExtLibrary) {
    let script = document.createElement('script');
    script.src = window.txGoMapsExtLibrary;
    script.async = true;
    document.head.appendChild(script);
  }
});`

**Comment by mhirdes** [comment]
in v7 we added the parameter loading=async
