### ISSUE TITLE
Uncaught TypeError: element.gomapsext is not a function & Cannot read properties of undefined (reading 'gme')

### ISSUE THREAD

**Issue by bh-teufels** [mhirdes/go_maps_ext#117]
I get the following errors

Uncaught TypeError: element.gomapsext is not a function 
in 
```
const element = document.getElementById(gme.mapSettings.id);
element.gomapsext(gme);
```

and

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'gme')
in
```
maps.forEach(function (el) {
  el.gomapsext.controller = new GoMapsExtController(el, el.gomapsext.gme);
  el.gomapsext.controller.initialize();
});
```

TYPO3 12.4.12
go_maps_ext 6.1.1

Extension Settings:
basic.include_manually = FALSE
basic.include_google_api_manually = FALSE
basic.footerJS = TRUE

(basic.footerJS = FALSE same Errors)

**Comment by bh-teufels** [comment]
go_maps_ext 6.1.0 working

**Comment by mhirdes** [comment]
Do you inlcude some JS by yourself? The current state is this:
https://github.com/mhirdes/go_maps_ext/blob/main/Resources/Public/Scripts/gomapsext.js#L739

**Comment by bh-teufels** [comment]
not any maps related js
i include jquery & gsap in the footer

**Comment by mhirdes** [comment]
But where does this come from (file, line):


```
const element = document.getElementById(gme.mapSettings.id);
element.gomapsext(gme);
```

**Comment by mhirdes** [comment]
Thanks for your feedback

**Comment by kitzberger** [comment]
@mhirdes, glad I came across this issue here. Would have expected a breaking change in a patch release.
