### ISSUE TITLE
MissingKeyMapError

### ISSUE THREAD

**Issue by CarstenHager** [mhirdes/go_maps_ext#15]
Hey Marc,

hast du eine Idee woran das liegen könnte?

![screenshot 2016-07-03 21 24 39](https://cloud.githubusercontent.com/assets/5907780/16547171/a7b42172-4164-11e6-95cc-30d00d64479b.png)

**Comment by CarstenHager** [comment]
MissingKeyMapError zeigt mir der Firebug an

**Comment by glucka** [comment]
Hi, ich habe das gleiche problem wobe habe ein API key bei die konstanten angegeben.
Danke ;)

**Comment by glucka** [comment]
Ahh das letzte Github version ist schon ok! Wunderbar! Danke für das tolle Extension!!!
