### ISSUE TITLE
Maps not saveable

### ISSUE THREAD

**Issue by steffenk** [mhirdes/go_maps_ext#20]
Hi,

with latest TYPO3 (8.6.1, 8.7.0-dev) it's not possible to save a map in BE.
Title, width and height are not saved after filling out and saving, they are empty again.
![bildschirmfoto 2017-03-27 um 16 35 32](https://cloud.githubusercontent.com/assets/234874/24361913/86258004-130b-11e7-8824-219f39347cc9.png)

**Comment by mhirdes** [comment]
Hi. Sry for that late answer. Tested it again and it works. It was temporary a core problem.
