### ISSUE TITLE
MarkerCluster style example

### ISSUE THREAD

**Issue by stroebjo** [mhirdes/go_maps_ext#22]
I want to change the styling of the cluster icon. I looked at Pull Request https://github.com/mhirdes/go_maps_ext/pull/16 and when I understood this correctly you should be able to overwrite the styling using a [JSON object](https://googlemaps.github.io/js-marker-clusterer/docs/reference.html) in the `Marker Cluster style code` field. But when I enter a simple `{textColor: "#fff"}` it causes a JavaScript error in the frontend. 

Is there an example how to correctly use this setting?

Thanks!

**Comment by mhirdes** [comment]
Hey. sry for that late answer but you can easily configure the style here https://mapstyle.withgoogle.com/ 
There you get a JSON code which you can copy & paste in the field Marker Cluster style code.

**Comment by MartinH0** [comment]
May I reopen this Issue as I just generated my JSON code and pasted it in the Marker Cluster Style field but it does not change anything in the Frontend.

I'm in the latest v3.1.1
