### ISSUE TITLE
API key need or not?

### ISSUE THREAD

**Issue by vajdajana** [mhirdes/go_maps_ext#25]
Hi Marc.

Thank you for your work. There is a little misunderstanding for me:

https://docs.typo3.org/typo3cms/extensions/go_maps_ext/Introduction/Index.html
=> "Uses Version 3 of the Google Maps API, no API key needed"

https://maps-apis.googleblog.com/2016/06/building-for-scale-updates-to-google.html
=> "We no longer support keyless access"

BR, János

**Comment by mhirdes** [comment]
Hey János,

thanks for report. I missed to update the introduction section. It's now fixed.

Kind reagards,
Marc
