### ISSUE TITLE
Google API Key doesn't work in frontend

### ISSUE THREAD

**Issue by swdesigntsit** [mhirdes/go_maps_ext#27]
The Google API key is missing when loading a page in the frontend.
I'm using TYPO3 8.7.3 and the current developer version of go_maps_ext, downloaded on 29th of Aug.
I already fixed the issue by basicly changing the name of setting for the API key. Please find enclosed the patch for this issue.

[go_maps_ext-2017_08_29.patch.zip](https://github.com/mhirdes/go_maps_ext/files/1262835/go_maps_ext-2017_08_29.patch.zip)

**Comment by mhirdes** [comment]
Hey. Thanks for your report. A pull request would be cool.

But to be honest, I don't know what your problem is? you can set `plugin.tx_gomapsext.settings .googleMapsLibrary` and `plugin.tx_gomapsext.settings.apiKey`. https://github.com/mhirdes/go_maps_ext/blob/master/Configuration/TypoScript/setup.txt

And in the Controller they will be read...
https://github.com/mhirdes/go_maps_ext/blob/master/Classes/Controller/MapController.php

**Comment by swdesigntsit** [comment]
Sorry, my 'bug report' was a little short.
Setting the API key in the Page TS constants only worked for the backend module.
But when rendering the page in the frontend the API key settings could not be read
by the extension, resulting in an error message from the Google Maps API.
I don't know why this behaviour occurs, but when using my patch everything is fine
without changing Page TS constants or anything else.
The API key was only set once in the entire TypoScript tree, so no second constant
declaration was overriding the first one with an empty value.

I further removed the strings with the URL of the Google Maps API from the MapController and the
LocationUtility, since it makes maintainance easier and the code less prone to bugs
in case the URL changes (or the GM API version).
And the patch prevents the rendering of Google Maps in the frontend in case the API key
or the GM API URL is missing. This behaviour could be parametrized e.g. through a constant
in the Page TS.

Just created the pull request. Sorry, I'm new to using GIT. I'm more of an old school Linux guy
that likes to create patch files ;-)

**Comment by mhirdes** [comment]
Hey, sry but I think this has to do sth. with your setup. Please check your project. If you want to, we can take a look together. But this changes are not necessary. You only rename a setting and add some more if statements. That's why I refused your request.
