### ISSUE TITLE
default_type field in Backend is missing

### ISSUE THREAD

**Issue by vajdajana** [mhirdes/go_maps_ext#29]
Hi,
the "default_type" field in Backend (map configuration) is missing.
Bugfixing maybe in TCA?
go_maps_ext/Configuration/TCA/tx_gomapsext_domain_model_map.php
thx.
BR, János
![go_maps_ext_default_type](https://user-images.githubusercontent.com/8311778/30114749-faa159d4-9318-11e7-9a6d-a1967c9a55c7.png)

**Comment by mhirdes** [comment]
Hi,

you find the default type in the tab 'Initial'. Please check also your user rights and if you use the current version of this extension.

Kind Regards,
Marc
