### ISSUE TITLE
address / map field (TCA config)

### ISSUE THREAD

**Issue by vajdajana** [mhirdes/go_maps_ext#32]
Hi,

I have found in the file:
go_maps_ext/Configuration/TCA/tx_gomapsext_domain_model_address.php:
'map' => [
	'config' => [
		'type' => 'inline',
		'foreign_table' => 'tx_gomapsext_domain_model_map',
		'MM' => 'tx_gomapsext_map_address_mm',
		'MM_opposite_field' => 'map',
	],
],
Is it OK? Or a bug? (MM_opposite_field)
(https://docs.typo3.org/typo3cms/TCAReference/7.6/Reference/Columns/Select/#mm-opposite-field)

Regards,
János

**Comment by mhirdes** [comment]
Hey. Thansks for the hint. IMO it should work, or what is your suggestion?
