### ISSUE TITLE
Marker via TypoScript

### ISSUE THREAD

**Issue by maximaexchen** [mhirdes/go_maps_ext#36]
I could not find, or there is no possibility to set custom marker via TypoScript?
If not, then it would be more a feature request.

I tried in constants and setup
plugin.tx_gomapsext.settings.marker = fileadmin/images/pin.png

Regards

Update:
Missleading Error-message.
I got the wrong url to a youtube video
Then everything is working fine.

**Comment by mhirdes** [comment]
Hi. Currently not. You can edit the web/typo3conf/ext/go_maps_ext/Resources/Private/Partials/Map/Assign.html on line 90. Of course copy the partial and add the partial root path. You can also add a pull request if you like to. Kind Regards, Marc
