### ISSUE TITLE
Addresses selected in map are ignored

### ISSUE THREAD

**Issue by steffenk** [mhirdes/go_maps_ext#43]
If you select addresses in a map, they are ignored, as the controller use pid for finding addresses.

I patched the controller to use the selected one, and use the pid only if nothing is selected:

if ($map->getAddresses()) {
		    $addresses = $map->getAddresses();
            } else { ...

**Comment by mhirdes** [comment]
Only when u set a storage pid. Or am I am wrong?

**Comment by steffenk** [comment]
no, it's a general thing. IMHO if you hav a map with selected adresses, this should be respected first. If you set a storagePid, it should select adresses from that Pid. Otherwise you can't show only sa defined set of addresses, or you have to spread them over different folders, which does not make sense to me.
See here the complete piece of code, which works perfect for me:

`// find addresses
        $pid = $this->settings['storagePid'];
        if ($map->getAddresses()) {
            $addresses = $map->getAddresses();
        } else {
            if ($pid) {
                if ($pid == 'this') {
                    $addresses = $this->addressRepository->findAllAddresses($map, $GLOBALS['TSFE']->id);
                } else {
                    $addresses = $this->addressRepository->findAllAddresses($map, $pid);
                }
            } else {
                $addresses = $map->getAddresses();
            }
        }`

**Comment by mhirdes** [comment]
Thanks. This behaviuor is used in 3.x
