### ISSUE TITLE
Cant save in 3.0.0-dev

### ISSUE THREAD

**Issue by M4rt1n17** [mhirdes/go_maps_ext#47]
I just updated (from 2.5.0) to 3.0.0-dev because I'm on Typo3 9.4.0 and 9.5.0 (two installations) but when I update I cant save any Maps anymore.

It shows me: 	

```
Oops, an error occurred!
An exception occurred while executing 'SELECT `geolocation` FROM `tx_gomapsext_domain_model_map` WHERE `uid` = ?' with params [1]: Unknown column 'geolocation' in 'field list'
```

Am I doing something wrong or is it there a bug?

**Comment by PascaleBeier** [comment]
Seems like you haven't run the Database Update Wizard yet

**Comment by M4rt1n17** [comment]
Thats true, that was the issue.
Thanks for pointing that out
