### ISSUE TITLE
Maps Overlay in Typo3 9

### ISSUE THREAD

**Issue by KotteBW** [mhirdes/go_maps_ext#48]
Hi, can I report a possible error for the 'version' => '3.0.0-dev' on Typo3 9.5.2?

We have an issue with the overlay and the controls settings. No zoom, pan, streetview or fullscreen buttons are appearing in the frontend. No matter what settings are used in the map.
Unfortunately there is no error message in the JS console.

The features like "maptype" (satellite/hybrid) and "list" are working.

**Comment by mhirdes** [comment]
Hi. In my case all controls are visible. The pan control is deprecated and now removed. Please try again.

**Comment by M4rt1n17** [comment]
I can confirm its working on TYPO3 9.5.3.
But actually v2.7.0 is not working properly. (just tested on TYPO3 8.7 but a strange search field appears on top of the Map.

**Comment by KotteBW** [comment]
We are using the 3.0.1-dev version and TYPO3 9.5.1 

In Map Settings in Controll tab only scale settings is working - Streetview, Fullscreen and Zoom Buttons are not appearing.  Are there any other settings that are preconditions for this?

![image](https://user-images.githubusercontent.com/25739632/51519243-ad7dcb80-1e20-11e9-9194-72c9fe59738e.png)

**Comment by mhirdes** [comment]
No, they are deprecated by the Google Maps API
