### ISSUE TITLE
By resize of windows its falling back to standard

### ISSUE THREAD

**Issue by M4rt1n17** [mhirdes/go_maps_ext#49]
When I'm using this extension on mobile devices on Chrome and zoom in. Then scroll (the page, not the map) down and up which is causing the window of Chrome getting smaller and bigger because of the URL-Bar. This is making this extension losing its zoom and jumpes back to standard.

Versions:
Typo3 v9.5.3
go_maps_ext v3.0.0

I noticed on some Wordpress G-Maps Extensions this behaviour is fixed but was there some years ago. Can you pls try to fix this?
If you want to I will make a video where this glitch is shown

**Comment by mhirdes** [comment]
Hi, the resize event will now only be fired, if the map width changes. Does that work for you?

**Comment by M4rt1n17** [comment]
Damn man u did it!
Thanks, its working perfectly on mobile and desktop.
Would be awesome of you could release the stable v3.0.1


Thanks for this fix!
