### ISSUE TITLE
Preview function not working in Internet Explorer 11

### ISSUE THREAD

**Issue by TFaehrmann** [mhirdes/go_maps_ext#50]
Hi, 
i got the following error in the browser console by using the preview function:

jQuery.Deferred exception: Unable to get property '_displayResult' of undefined or null reference

original german version:

jQuery.Deferred exception: Die Eigenschaft "InfoWindow" eines undefinierten oder Nullverweises kann nicht abgerufen werden. 
TypeError: Die Eigenschaft "InfoWindow" eines undefinierten oder Nullverweises kann nicht abgerufen werden.
at GoMapsExt.Controller.prototype.initialize (https://example.com/typo3conf/ext/go_maps_ext/Resources/Public/Scripts/jquery.gomapsext.js?1547479101:63:10)
at GoMapsExt.Controller (https://example.com/typo3conf/ext/go_maps_ext/Resources/Public/Scripts/jquery.gomapsext.js?1547479101:52:13)
at $.fn.gomapsext (https://example.com/typo3conf/ext/go_maps_ext/Resources/Public/Scripts/jquery.gomapsext.js?1547479101:718:13)
at Anonymous function (https://example.com/typo3temp/assets/js/d4b3589af2.js?1547041515:101:5)
at j (https://example.com/typo3conf/ext/slickcarousel/Resources/Public/JavaScript/jquery.min.js?1504703152:2:29941)
at Anonymous function (https://example.com/typo3c

SCRIPT5007: Die Eigenschaft "InfoWindow" eines undefinierten oder Nullverweises kann nicht abgerufen werden.
jquery.min.js (2,31635)

Iam using Typo3 8.7.22 with the Introduction Package.
Also dosent work with Typo3 9.5.3

You can rebuild the error by using the following steps:
1: Install Typo3 with Introduction Package
2: Install go_maps_ext and include setup
3: Add the line to constants "plugin.tx_gomapsext.settings.preview.setCookieToShowMapAlways = 1"
4: Create a map and att the plugin to a side
5: Open the page in frontend and try out

**Comment by mhirdes** [comment]
Did you already insert an address?

**Comment by TFaehrmann** [comment]
Sorry for the late response. 
i saw that this issue is open so i created a new test environment.

TYPO3 9.5.9 with the Introduction Package.
I followed the steps from my previous path and add aditionally an address.

Still dosent show the map in ie11.
Chrome, Firefox and Edge works like expected.

**Comment by mhirdes** [comment]
Sry, but in my enviroment it works. I can only offer you to take a look together via TeamViewer or you send me a link. You can contact me on Slack

**Comment by wuestefeld** [comment]
We have fixed the issue and created 2 pull-requests. With defined google meta tag (e.g. bootstrap_package) the google-variable was not undefined in IE, so the init-proccess started even though the google-lib wasn't loaded..

**Comment by mhirdes** [comment]
@wuestefeld thanks a lot. I modified your statements a little bit, checkout the branch 3x
