### ISSUE TITLE
Fixing G-Maps URL and prevent redirect.

### ISSUE THREAD

**Issue by M4rt1n17** [mhirdes/go_maps_ext#51]
When I click on calculate route it brings me to G-Maps.
But it calls the Link:
https://**maps**.google.com/maps?daddr=[address]
then Google redirects it to:
https://**www**.google.com/maps?daddr=[address]
and then to:
https://www.google.com/maps/dir/[address]

Pls change all G-Maps links to the subdomain "www" instead of "maps".
And maybe adapt these maps URLs https://developers.google.com/maps/documentation/urls/guide

Thanks

**Comment by mhirdes** [comment]
Hi, thanks a lot for your hint. It's online. A release will be published in the next days.
