### ISSUE TITLE
Custom SVG Marker does not get shown in Internet Explorer

### ISSUE THREAD

**Issue by MartinH0** [mhirdes/go_maps_ext#53]
Typo3: 8.7 & 9.5
go_maps_ext: v2.5 & 3.1 (& 3.1.1-dev)

Actually on none of my TYPO3 Sites custom Markers (also they are all SVG) are shown in latest IE.
In Chrome, FireFox, Opera & Safari its working flawless.
Maybe this is a IE compatibility issue of this extension?

**Comment by mhirdes** [comment]
we don't have an exception for the IE. Maybe it is more Google or IE related.
