### ISSUE TITLE
englisch lang instead of german

### ISSUE THREAD

**Issue by MartinH0** [mhirdes/go_maps_ext#55]
My complete Site is set to german, also the Map and all the locations I added.
In the frontend the language also is german.

But when I call the G-Maps mobile it shows me "use two fingers to zoom" instead of "nutzen zwei Finger um zu zoomen".

I have the same version running on another TYPO3 instance, there it is german, but its all the same.
Maybe my API Key is englisch at one site?
If so: can this plugin force the language to the one selected in TYPO3?

**Comment by M4rt1n17** [comment]
Found a way to force the language.

https://stackoverflow.com/questions/2662889/how-to-indicate-the-language-in-the-google-maps-api

Could you pls implement this, to force the language if itsnot by default right?
A option to force it dynamically to the `config.language` as this would also work if you are on a multilanguage setup.

Thanks!

**Comment by mhirdes** [comment]
we don't force a language, because Google automaticaly detects your browser language.

**Comment by MartinH0** [comment]
Hm seems you do. But just happens at one Installation.

![go_maps_ext](https://user-images.githubusercontent.com/17692860/58342838-d0ad9b80-7e51-11e9-9459-3a9317668d49.PNG)

**Comment by MartinH0** [comment]
Still same issue.
My Page is made in two languages
1. german
2. englisch

no matter what I do the snipped in the frontend looks like this:

`<script src="//maps.google.com/maps/api/js?v=weekly&amp;key=[***API-Key***]&amp;language=en" type="text/javascript"></script>`
Where I want to point to **`&amp;language=en`** this is forcing the map to always display in englisch.

100% sure I included the german map on the german page and the englisch on the englisch site but its always in englisch (forced)

Is there a way to delete the `&amp;language=en` part?

Best regards
Martin

**Comment by mhirdes** [comment]
Sry for the late response. is online
