### ISSUE TITLE
[Feature] Option to hide unnecessary things (pio.business, etc)

### ISSUE THREAD

**Issue by MartinH0** [mhirdes/go_maps_ext#56]
I would love the option to hide all other commercial and non-commercial results in the map.

The G-Maps APIv3 gives the possibility to do so:

https://developers.google.com/maps/documentation/javascript/examples/hiding-features
https://developers.google.com/maps/documentation/javascript/styling (this is for a complete Styling guide)

A more simplyfied/cleaner map would be awesome!!

**Comment by mhirdes** [comment]
you can extend the JavaScript config, but this I won't add to the extension. Also you can now style each map as you want already in the extension, use styledMapCode https://docs.typo3.org/typo3cms/extensions/go_maps_ext/User/Index.html
