### ISSUE TITLE
Disable Google Javascript

### ISSUE THREAD

**Issue by fritzdacat** [mhirdes/go_maps_ext#59]
would it be possible here:

        if (! $ this-> settings ['preview'] ['enabled']) {
            $ pageRenderer -> {$ addJsMethod. 'Library'} (
                'Google Maps',
                $ This-> google maps library,
                'Text / javascript'
                false
                false
                ''
                true
            );
        }

add another option that you can disable the javascript, even if you do not want to use the "Preview Enable" version of the extension?

The background is that we like to embed the Javascript ourselves to control it over "Cookiebot".

It may also be that the Google Javascript is already involved once. Then it would be twice in the code.

There is the option:
Include JS from extension manually
basic.include_manually (boolean)

Unfortunately this only works for all other javascripts.

**I would need this option for the TYPO3 8 version of go_maps_ext**

**Comment by mhirdes** [comment]
please test and give feedback

**Comment by fritzdacat** [comment]
https://github.com/mhirdes/go_maps_ext/pull/60
