### ISSUE TITLE
Error in typo3 7.4

### ISSUE THREAD

**Issue by hhjse** [mhirdes/go_maps_ext#6]
I get this error, when I install go_maps_ext in Typo3 7.4.0 and go to the Admin Tool > Extension:

```
Uncaught TYPO3 Exception
#1382276561: The package "go_maps_ext" depends on "typo3/cms" which is not present in the system.
```
When I remove require typo3/cms (line 20, file composer.json) it works ...

**Comment by liayn** [comment]
The require has to be
```
  "require": {
    "typo3/cms-core": "6.2.0 - 7.4.99"
  },
```
In your emconf you can kick the dependencies on extbase and fluid, these are not necessary anymore.

Furthermore I highly recommend to not set a dependency valid up to 7.99.99. You never know what is changed with 7.5 for instance, so you should better release a new version, which declares new compatibility, once you tested it.

Thanks.
