### ISSUE TITLE
[Feature Request] TYPO3 v10 Support

### ISSUE THREAD

**Issue by MartinH0** [mhirdes/go_maps_ext#65]
Atm I can not use this extension in a TYPO3 v10 Installation.
I can configure things but when it comes to rendering and displaying them in the frontend this Error gets shown:
![go_map_ext](https://user-images.githubusercontent.com/17692860/70230783-61e2c080-1759-11ea-958f-1f3c3a860786.png)

Hope that helps.

Setup:
TYPO3: v10.2
go_map_ext: 3.1.1-dev (latest as of the date of writing this)

**Comment by mhirdes** [comment]
We don't provide a version for each single TYPO3 v10. We will provide a version for the v10 LTS

**Comment by MartinH0** [comment]
I can understand this, but if it works for TYPO3 v10.2 is will also work for TYPO3 v10.5 (LTS) as there will not be any changes related to this extension.

Means all the Changes are madr from v9 to v10, not in between v10.0.0 and v10.2.2.
Means: the Version that will work for v10.0.0 will also work for all other v10 versions.

**Comment by bitwelle** [comment]
Is there maybe a development version that can be used for TYPO3 10 with composer? Or do i have to adapt it completely on my own and submit a new branch?

**Comment by MartinH0** [comment]
> Is there maybe a development version that can be used for TYPO3 10 with composer? Or do i have to adapt it completely on my own and submit a new branch?

Seems like you would have to do it on your own as @mhirdes does not want to make it compatible before TYPO3 10 (LTS) is released officially as a LTS release.

> We don't provide a version for each single TYPO3 v10

I think this leads to a wrong thing as there is no need for "each" single TYPO3 v10 version as it would work on every TYPO3 v10 version when it works on TYPO3 v10.0.0.
This is due to all the changes (related to this extension) are done there, after this nothing changed (and nothing will change due to the roadmap) what could break this extension.

But thats how it is.

**Comment by mhirdes** [comment]
Hi @bitwelle I can provide a dev branch for the v10. I will provide a branch hopefully until the end of the week.

**Comment by mhirdes** [comment]
you can now use the master branch for TYPO3 v10. I am not fully done with testing, but to show a map should work

**Comment by MartinH0** [comment]
> I am not fully done with testing, but to show a map should work

Its true 4.0.0-dev is working under TYPO3 v10. Thanks!!
Could you have a quick look at this:

- In in the constants the part "PLUGIN.TX_GOMAPSEXT (14)" dissapeared and its not possible to tell this extension to use an API key anymore.
- map itself is working but map-points (locations) are not. Everything is located somewhere is south russia near georgia

Anyway thanks for making the base TYPO3 v10 compatible

**Comment by mhirdes** [comment]
Thanks for your report. Did you include the typoscript of go_maps_ext? Because I can add the ApiKey in the Constant Editor also in v10.

**Comment by MartinH0** [comment]
Yeah sorry did not include the typoscript again after reinstalling the extension.

Now everything works so far. Thanks, was my fault
