### ISSUE TITLE
Please make new Release (3.1.1)

### ISSUE THREAD

**Issue by MartinH0** [mhirdes/go_maps_ext#66]
Due to some issues (https://github.com/mhirdes/go_maps_ext/issues/57, https://github.com/mhirdes/go_maps_ext/issues/55, https://github.com/mhirdes/go_maps_ext/issues/49) the latest official release will not work properly. Especially because of https://github.com/mhirdes/go_maps_ext/issues/57. Please release the next Release with all this fixed included. The latest version available on the TER ([LINK](https://extensions.typo3.org/extension/go_maps_ext/)) will not work on most of the TYPO3 v9 Versions.

A Fix-Release (including all the good fixes) could easily fix this.

**Comment by mhirdes** [comment]
Done https://github.com/mhirdes/go_maps_ext/commit/7c7dc1d98beac801a08a585150fdcc148c227482
