### ISSUE TITLE
on saving an address latitude and longitude will get cutted and doesnt include decimals points anymore

### ISSUE THREAD

**Issue by wimbschimmelpfennig** [mhirdes/go_maps_ext#72]
Im using the current TER version. If I click on "Update by Address" it prefills lat and long to the correct coordinates. If I click "save" and the form reload the entries have updated and all data behind the dots (.) are cut.

If I remove the Double6Evaluator from TCA the fields save correctly. but get displayed with a comma (,) instead, which confuses the map in the backend

**Comment by mhirdes** [comment]
Sry, but I can't reproduce this. Which Browser, GoMapsExt, TYPO3 version do u use?
