### ISSUE TITLE
persistence map v10

### ISSUE THREAD

**Issue by prdt3e** [mhirdes/go_maps_ext#74]
sys_category in setup.typoscript

[87623](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html)

**Comment by manuelportela** [comment]
Dear @prdt3e 

is this the only issue for v10? I'm currently collecting my usual suspect extensions for the next/upcoming projects. I could live with small composer patches for a little while but may stick a little longer with 9.5 if i missing out on my favs.

**Comment by rwitschas** [comment]
@mhirdes 
Is an "official" TYPO3 V 10.4 support of the extension planned for the next weeks? We have to decide whether we 

- update from 8.7 to 9.5 with having this extension still being supported or 
- update from 8.7 to 10.4 with having this extension not being supported and leaving it out.

Thanks in advance!

**Comment by mhirdes** [comment]
you can allready use the master. release will be out during the next week

**Comment by mhirdes** [comment]
Thanks for the advice
