### ISSUE TITLE
Make API key konfigurable in FlexForm of Plugin

### ISSUE THREAD

**Issue by foobar13372** [mhirdes/go_maps_ext#76]
Currently the API is only configurable via TypoScript. This makes the Plugin useless for editors that do not have access to TypoScript but are allowed to edit the plugin.
There should be a way for the plugin to override the API key from the settings.

It should fallback like this: "Flexform ?: TypoScript ?: extension configuration".

This way editors can add their own maps without admin interference.

**Comment by mhirdes** [comment]
do you really need an API key for each map? IMO it makes more sense to add an API key for one TYPO3 or site, but not for each Plugin

**Comment by foobar13372** [comment]
We have a setup with 160+ users and 200+ domains. Everyone has it's own Google Account. Each domain has at least one editor. Each editor has access to the maps plugin. Your way would mean that we have to communicate to 160+ people that they please send us their 200+ keys so tha twe can enter them in a configuration file they can not see. This add so much confuguration and communication overload which can easily be avoided if there's the possibility to overide the centrally configured key per map.

Google API keys are surely to be maintained by the client, not by the devs. They blong to the "content/marketing domain" by the client, not to the "technical domain" of the TYPO3 system as such.

**Comment by prdt3e** [comment]
@foobar13372 
Your approach is not bad.
in fact, the api-key has to be exchanged gladly and often without a developer.
Maybe additional via Flexform? Allow in extension configuration (the flexform).

**Comment by mhirdes** [comment]
Would it make more sens to add a new table "Google Maps API Keys"? I dont like the idea to enter a key in each map. Because when I use a key for multiple maps and this key changes I have to change it for all maps separatly. Alos I like the idea to add it in the site configuration or to have the key on a more abstract level. So I don't need to assign a key for each map. We can also write on Slack to this topic.

**Comment by prdt3e** [comment]
That's a great idea.

**Comment by mhirdes** [comment]
sry for the late response. a suggestion is now in master
