### ISSUE TITLE
zoomControlType not set in rendered JAVASCRIPT

### ISSUE THREAD

**Issue by 123AltmarkAgentur** [mhirdes/go_maps_ext#77]
Hello,
i get a javascript error in rendered js-file, because the option "zoomControlType" has no value!

**zoomControlType: ,**

If i set it manually, everthing works fine and the map is rendered!
zoomControlType: **0**,

Where can i set this value?

Typo3: 9.5.19
Ext: 3.2.0

Best reguards

<img width="751" alt="zoomControlType not set" src="https://user-images.githubusercontent.com/5715991/86948819-0264ed00-c14e-11ea-80f0-60bab72ae1d1.png">

**Comment by DesignGalaxie** [comment]
Same problem here. 
Typo3 9.5.19
Ext: 3.2.0 (I really like your extension by the way)
No other extension installed. 

Temporary solution for me, was a downgrade to 2.6.0 of go_maps_ext (uses a retired google maps api) in my 9.5.19 instance. In 2.6.0 in the plugin configuration you can choose in the "Control" Tab the "Type of zoom Control" (Default / Small / Large). This value is written into the generated javascript file as the value for zoomControlType (Default = 0). 

It seems to me, that versions > 3.x.x don't offer the "Type of zoom control" options in the flexform of the plugin anymore. So I would assume that this error affects all branches of 3.x.x / TYPO3 9.5.x which means, that the map is not loading. As a fan of the zoomControlType "small" it would be great, if the options in the control palette, for the zoomControlType could come back (that would also solve the javascript issue).

Best regards

**Comment by mhirdes** [comment]
https://developers.google.com/maps/documentation/javascript/releases#3.22 

> The Zoom control is available in only one style, and google.maps.ZoomControlStyle is therefore no longer available.

Hey, as you can see above, the zoom control style option was depcrecated. Therefore I also removed this option.
