### ISSUE TITLE
Invalid Argument when show_categories = 1/true

### ISSUE THREAD

**Issue by dennismetz** [mhirdes/go_maps_ext#82]
PHP Warning: Invalid argument supplied for foreach() in .../ext/go_maps_ext/Classes/Controller/MapController.php line 159

Additionally i get a syntax error if the fields 
"imageHeight", 
"imageWidth" and 
"infoWindowLink" are not set (empty).

To fix the problem the values must be in quotes (go_maps_ext/Resources/Private/Partials/Map/Assign.html):

        imageWidth: '{address.imageWidth}',
        imageHeight: '{address.imageHeight}',
        infoWindowLink: '{address.infoWindowLink}',

**Comment by mhirdes** [comment]
Hi. For the first error, which Version of go_maps_ext do you use?

**Comment by dennismetz** [comment]
Sorry for the missing info:

TYPO3 v10.4.16
Composer installation
go_maps_ext: 4.0.0
PHP 7.3-7.4

**Comment by mhirdes** [comment]
should be fixed in master. thanks for reporting
