### ISSUE TITLE
Map width / height in %

### ISSUE THREAD

**Issue by Ra-fiki** [mhirdes/go_maps_ext#87]
In TYPO3 10.4.21 for 4.0.1 of extension
It seams that if in width and height I put w: 100% and h: 100%
map disapear in frontend O.o

**Comment by mhirdes** [comment]
This is more a CSS issue. If you set the height to 100% all elements above should also have a height. 

If you set the height to 100% and the element on level up has a height of 0, then also the container has a height of 0. I would recommend a fixed height or 100vh or sth. else.
