### ISSUE TITLE
T3 11.5 - go_maps_ext  5.0.0 - Marker layout Error

### ISSUE THREAD

**Issue by ingeniumdesign** [mhirdes/go_maps_ext#89]
in the new go_maps_ext 5.0. add a new png marker icon.

**Here the Error:**
png could not be resolved to a File or FileReference.

**Comment by ingeniumdesign** [comment]
Solution: You need a height and width!
Better is a fallback and not a Frontend Error

**Comment by mhirdes** [comment]
Hey,

where did you add the icon? I don't get the error.

Maybe you can contact me on slack.
