### ISSUE TITLE
class.tx_gomapsext_tca.php not loaded, when using Composer

### ISSUE THREAD

**Issue by InvisibleKind** [mhirdes/go_maps_ext#9]
When creating/editing record, no map is shown in BE.

In addition I'm getting such a message in BE, when trying to edit record:
```
TYPO3\CMS\Core\Utility\GeneralUtility::callUserFunction No class named tx_gomapsext_tca
```

The reason is, that file is not auto-loaded by Composer.

Workaround: add autoload-files section
```
"autoload": {
         "files": ["www/typo3conf/ext/go_maps_ext/class.tx_gomapsext_tca.php"]
    },
```

Better fix: make this file follow psr-4 and be located in "Classes\" folder.

**Comment by InvisibleKind** [comment]
And, actually same is with FE, because _composer.json_ form extension missing "autoload" section at all.

**Comment by mhirdes** [comment]
is fixed
