### ISSUE TITLE
Route Issue

### ISSUE THREAD

**Issue by icehawk-de** [mhirdes/go_maps_ext#91]
I'm using 4.1.0 with TYPO3 10.4.26.

I want to use the route feature: "Show particular route". 

I've added two addresses in the map.
![image](https://user-images.githubusercontent.com/19264337/161511801-9b96d308-871e-49da-8104-a6b833428c00.png)
Both addresses are valid. If I use the "normal" map, both markers are shown at the map.
If I activate "Show particular route":
![image](https://user-images.githubusercontent.com/19264337/161512320-b9f29315-a849-4603-b737-e4f6ca3ed9ea.png)
Then I get an error:
![image](https://user-images.githubusercontent.com/19264337/161512546-15ae8dbb-a0ad-46b3-be2c-c9da63f0fd9d.png)
What is my problem. The Api-Key? I don't have an api-key at the moment. Or something ese?

**Comment by mhirdes** [comment]
The missing API key could be a reason. But maybe here it is some miss configuration. 

I created a route again in my setup and it works as it should.

Maybe you can contact me on slack.

**Comment by icehawk-de** [comment]
Thanks for your help! No error!
Everything works fine!

After I included the API-Key for "Maps JavaScript API" I got an error that "Directions API" is missing for route.
I also activated this API and now the route ist shown.

The problem is, that the console shows only one error, not all errors, when the API-Key is missing.
