### ISSUE TITLE
scroll_zoom off does have any effect

### ISSUE THREAD

**Issue by sheydin** [mhirdes/go_maps_ext#93]
Please see screenshot. Tested with TYPO3 11.5.10 and go_maps_ext 5.0.1. Disregarding of the checkbox state the zoom control works.

<img width="263" alt="Bildschirmfoto 2022-05-19 um 21 25 28" src="https://user-images.githubusercontent.com/2332612/169386793-038fdc8e-7861-4b22-b93f-1142f5ffff5f.png">

**Comment by mhirdes** [comment]
Thanks for reporting. Google now allows only to enable or disable gestures. https://developers.google.com/maps/documentation/javascript/interaction

**Comment by mhirdes** [comment]
With new version of go_maps_ext this is fixed
