### ISSUE TITLE
[FEATURE] 2-click solution for GDPR

### ISSUE THREAD

**Issue by okroener** [mhirdes/go_maps_ext#94]
Hello,

we are using this extension and are quite happy.

However, we have the need for a 2-click solution, which means that a website visitor has to consent with Google Maps content and Google privacy. 

In that case, only a picture is shown and the user hast to actively accept the content by clicking a button etc.

Is that a festure that you plan to integrate in your extension? Or are there any other solutions already available?

Best Regards,

Oliver

**Comment by mhirdes** [comment]
Hey,

this is already documented.  https://docs.typo3.org/p/clickstorm/go-maps-ext/5.0/en-us/Introduction/Index.html#what-does-it-do and https://docs.typo3.org/p/clickstorm/go-maps-ext/5.0/en-us/Configuration/Reference/Index.html settings.preview.enabled.
