### ISSUE TITLE
PHP Warning: Undefined array key "ff" in MapController.php line 246

### ISSUE THREAD

**Issue by nhovratov** [mhirdes/go_maps_ext#98]
TYPO3 v11 / PHP 8.1 / go_maps_ext v5.1.0

PHP Warning: Undefined array key "ff" in /var/www/html/public/typo3conf/ext/go_maps_ext/Classes/Controller/MapController.php line 246

**Comment by andrekoller** [comment]
@nhovratov after an update?
settings['ff'] is empty, its set in flexform of the plugin
Just open the plugin CE and save again

**Comment by clickstorm** [comment]
https://github.com/mhirdes/go_maps_ext/commit/951063239c2a661a862d1bad000a9c8188cd1951 should prevent this error. I will release a new version

**Comment by nhovratov** [comment]
Yes, it was after an update. So it's already fixed, thanks!
